swagger: "2.0"

info:
  title: "Muter WS API"
  version: "1.0"

basePath: /v1.0

paths:
  /products/:
    get:
      operationId: "api.api.search"
      responses:
        '200':
          description: 'Fetch a list of products'
          schema:
            type: array
            items:
              $ref: '#/definitions/product'

definitions:
  product:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name: { type: string }
      description: {type: string}
      price:
        type: integer
        format: int64
      color: {type: string}
      size:
        type: integer
        format: int64